# Generated by Django 5.1.1 on 2024-09-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('L', 'Late'), ('A', 'Absent'), ('E', 'Early Leave')], default='A', max_length=1),
        ),
    ]
